# demo initial pose

demo_ini_pose:
  mov_time : 5.0
  left_position : [ 0.45 , 0.302 , 1.1 ]
  right_position : [ 0.45 , -0.302 , 1.1 ]


# line trajectory parameter

demo_line : 
  mov_time : 8.0						# [sec]
  via_num : 3
  via_time : [ 2.0 , 4.0 , 6.0 ]				# [sec]
  left_via_position:						# x , y , z [m]
    1 : [ 0.45 , 0.502 , 1.1 ]					
    2 : [ 0.45 , 0.302 , 1.1 ]
    3 : [ 0.45 , 0.302 , 0.9 ]
  left_tar_position : [ 0.45 , 0.302 , 1.1 ]			# x , y , z [m]
  right_via_position:						# x , y , z [m]
    1 : [ 0.45 , -0.502 , 1.1 ]				
    2 : [ 0.45 , -0.302 , 1.1 ]
    3 : [ 0.45 , -0.302 , 0.9 ]
  right_tar_position : [ 0.45 , -0.302 , 1.1 ]			# x , y , z [m]


# circle trajectory parameter

demo_circle : 
  mov_time : 7.0					# [sec]
  rot_angle : 360.0 					# [deg]
  cross_ratio : 0.0 					# 0.0 ~ 1.0
  radius : [ 0.0 , 0.0 , -0.15 ] 			# [m]
  normal_vector : [ 1.0 , 0.0 , 0.0 ]			# x , y , z
