# time parameter

mov_time : 3.0		# movement time

# target pose [deg]

tar_pose :
  1  : -32.60 	    # r_arm_sh_p1
  2  : -31.79 	    # l_arm_sh_p1
  3  : -59.11 	    # r_arm_sh_r
  4  :  82.16	    # l_arm_sh_r
  5  :   6.61 	    # r_arm_sh_p2
  6  :   1.6 	    # l_arm_sh_p2
  7  : -28.33 	    # r_arm_el_y
  8  :  47.21 	    # l_arm_el_y
  9  : -59.65 	    # r_arm_wr_r
  10 : -34.76 	    # l_arm_wr_r
  11 :   9.02 	    # r_arm_wr_y
  12 : -76.77	    # l_arm_wr_y
  13 :  -4.88 	    # r_arm_wr_p
  14 : -58.72 	    # l_arm_wr_p
  27 :   0.0	    # torso_y

