# time parameter

mov_time : 3.0		# movement time

# target pose [deg]

tar_pose :
  1  : -57.74 	    # r_arm_sh_p1
  2  :  -1.10 	    # l_arm_sh_p1
  3  : -60.30 	    # r_arm_sh_r
  4  :  76.36	    # l_arm_sh_r
  5  :  12.56 	    # r_arm_sh_p2
  6  : -38.77	    # l_arm_sh_p2
  7  : -37.51 	    # r_arm_el_y
  8  :  66.91 	    # l_arm_el_y
  9  : -59.05 	    # r_arm_wr_r
  10 : -36.13 	    # l_arm_wr_r
  11 :   8.73 	    # r_arm_wr_y
  12 : -73.24	    # l_arm_wr_y
  13 : -19.30 	    # r_arm_wr_p
  14 :  -4.76 	    # l_arm_wr_p
  27 :   0.0	    # torso_y

